### ISSUE TITLE
Add MPI_Remove_error_class, MPI_Remove_error_code, MPI_Remove_error_string

### ISSUE THREAD

**Issue by ZedThree** [mpiwg-ft/ft-issues#14]
It would be useful to add `Remove` counterparts to the `MPI_Add_error_*` functions. Some MPI implementations statically allocate error classes, so there is a hard upper limit on the number supported. This also makes it difficult for libraries to clean up after themselves

See [here](https://github.com/pmodels/mpich/issues/4341) for some further information on why this would be useful.

(Apologies if this is the wrong place for user suggestions! Happy to move this elsewhere if I could be pointed in the right direction)

**Comment by wesbland** [comment]
Yeah, this makes sense. In the meantime, this is a perfect opportunity for MPICH to demonstrate non-catastrophic errors (and PETSc's ability to handle them) by checking the return value of `MPI_Add_error_class`. 😄 

I suggest re-opening this in https://github.com/mpi-forum/mpi-issues since that's the place the MPI Forum uses to track work in progress. I'm happy to do that for you if you'd like.

**Comment by ZedThree** [comment]
Thanks! I wasn't sure whether to open it start in that repo or not -- thought it might need to go through a working group first. I'll go open it now.

**Comment by wesbland** [comment]
Thanks. I've put together a PR here (https://github.com/mpi-forum/mpi-standard/pull/166) by the way. We'll discuss this in the FTWG con call on Monday.
